# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Richie Bryan
email: your-email@domain.com

tagline: Freelance Web and Graphic Design that Illuminates your Brand

description: Richie Bryan is a professional graphic designer, artist and copywriter. He combines an eye for design with the business logistics of advertising and public relations to help clients develop their image and messaging. Core strengths include creative writing and digital design of print and web graphics.


baseurl: "/richiebryan" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
# permalink: /:categories/:title/

# paginate: 10
# paginate_path: "/blog/page:num"
# paginate_category: blog

gems:
 - jekyll-coffeescript
 - jekyll-paginate
